//
//Main Control Protocol
//- Android App(gRPC client) -> Main Server(gRPC server)
//- Edge Controller(gRPC client) -> Main Server(gRPC server)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: main_control.proto

package maincontrol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistererStatus int32

const (
	RegistererStatus_REGISTERER_STATUS_UNSPECIFIED    RegistererStatus = 0 // 상태정의 안한 경우 (default)
	RegistererStatus_REGISTERER_STATUS_NOT_REGISTERED RegistererStatus = 1 // 미등록 상태(차단기 통행 불가)
	RegistererStatus_REGISTERER_STATUS_REGISTERED     RegistererStatus = 2 // 등록된 상태(차단기 통행 가능)
	RegistererStatus_REGISTERER_STATUS_BLOCKED        RegistererStatus = 3 // 등록된 상태(차단기 통행 불가)
)

// Enum value maps for RegistererStatus.
var (
	RegistererStatus_name = map[int32]string{
		0: "REGISTERER_STATUS_UNSPECIFIED",
		1: "REGISTERER_STATUS_NOT_REGISTERED",
		2: "REGISTERER_STATUS_REGISTERED",
		3: "REGISTERER_STATUS_BLOCKED",
	}
	RegistererStatus_value = map[string]int32{
		"REGISTERER_STATUS_UNSPECIFIED":    0,
		"REGISTERER_STATUS_NOT_REGISTERED": 1,
		"REGISTERER_STATUS_REGISTERED":     2,
		"REGISTERER_STATUS_BLOCKED":        3,
	}
)

func (x RegistererStatus) Enum() *RegistererStatus {
	p := new(RegistererStatus)
	*p = x
	return p
}

func (x RegistererStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegistererStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_main_control_proto_enumTypes[0].Descriptor()
}

func (RegistererStatus) Type() protoreflect.EnumType {
	return &file_main_control_proto_enumTypes[0]
}

func (x RegistererStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegistererStatus.Descriptor instead.
func (RegistererStatus) EnumDescriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{0}
}

type BarnStatus int32

const (
	BarnStatus_BARN_STATUS_UNSPECIFIED BarnStatus = 0
	BarnStatus_BARN_STATUS_SAFE        BarnStatus = 1
	BarnStatus_BARN_STATUS_UNSAFE      BarnStatus = 2
)

// Enum value maps for BarnStatus.
var (
	BarnStatus_name = map[int32]string{
		0: "BARN_STATUS_UNSPECIFIED",
		1: "BARN_STATUS_SAFE",
		2: "BARN_STATUS_UNSAFE",
	}
	BarnStatus_value = map[string]int32{
		"BARN_STATUS_UNSPECIFIED": 0,
		"BARN_STATUS_SAFE":        1,
		"BARN_STATUS_UNSAFE":      2,
	}
)

func (x BarnStatus) Enum() *BarnStatus {
	p := new(BarnStatus)
	*p = x
	return p
}

func (x BarnStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BarnStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_main_control_proto_enumTypes[1].Descriptor()
}

func (BarnStatus) Type() protoreflect.EnumType {
	return &file_main_control_proto_enumTypes[1]
}

func (x BarnStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BarnStatus.Descriptor instead.
func (BarnStatus) EnumDescriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{1}
}

// 축사 등록자 명부
type Registerer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BarnId       uint64           `protobuf:"varint,2,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
	Name         string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PlateNumber  string           `protobuf:"bytes,4,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	PhoneNumber  string           `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RegisterTime string           `protobuf:"bytes,6,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	Status       RegistererStatus `protobuf:"varint,7,opt,name=status,proto3,enum=maincontrol.RegistererStatus" json:"status,omitempty"`
	Note         string           `protobuf:"bytes,8,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *Registerer) Reset() {
	*x = Registerer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Registerer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registerer) ProtoMessage() {}

func (x *Registerer) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registerer.ProtoReflect.Descriptor instead.
func (*Registerer) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{0}
}

func (x *Registerer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Registerer) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

func (x *Registerer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Registerer) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *Registerer) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Registerer) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

func (x *Registerer) GetStatus() RegistererStatus {
	if x != nil {
		return x.Status
	}
	return RegistererStatus_REGISTERER_STATUS_UNSPECIFIED
}

func (x *Registerer) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 축사 정보
type Barn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address           string     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Latitude          float64    `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude         float64    `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PhoneNumber       string     `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	RegisterTime      string     `protobuf:"bytes,7,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	OwnerName         string     `protobuf:"bytes,8,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerPhoneNumber  string     `protobuf:"bytes,9,opt,name=owner_phone_number,json=ownerPhoneNumber,proto3" json:"owner_phone_number,omitempty"`
	Status            BarnStatus `protobuf:"varint,10,opt,name=status,proto3,enum=maincontrol.BarnStatus" json:"status,omitempty"`
	Note              string     `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	ControllerSerial  string     `protobuf:"bytes,12,opt,name=controller_serial,json=controllerSerial,proto3" json:"controller_serial,omitempty"`
	ControllerVersion string     `protobuf:"bytes,13,opt,name=controller_version,json=controllerVersion,proto3" json:"controller_version,omitempty"`
}

func (x *Barn) Reset() {
	*x = Barn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Barn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barn) ProtoMessage() {}

func (x *Barn) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barn.ProtoReflect.Descriptor instead.
func (*Barn) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{1}
}

func (x *Barn) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Barn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Barn) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Barn) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Barn) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Barn) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Barn) GetRegisterTime() string {
	if x != nil {
		return x.RegisterTime
	}
	return ""
}

func (x *Barn) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Barn) GetOwnerPhoneNumber() string {
	if x != nil {
		return x.OwnerPhoneNumber
	}
	return ""
}

func (x *Barn) GetStatus() BarnStatus {
	if x != nil {
		return x.Status
	}
	return BarnStatus_BARN_STATUS_UNSPECIFIED
}

func (x *Barn) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Barn) GetControllerSerial() string {
	if x != nil {
		return x.ControllerSerial
	}
	return ""
}

func (x *Barn) GetControllerVersion() string {
	if x != nil {
		return x.ControllerVersion
	}
	return ""
}

// 사용자 등록
type AddRegistererRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registerer *Registerer `protobuf:"bytes,1,opt,name=registerer,proto3" json:"registerer,omitempty"`
}

func (x *AddRegistererRequest) Reset() {
	*x = AddRegistererRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRegistererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRegistererRequest) ProtoMessage() {}

func (x *AddRegistererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRegistererRequest.ProtoReflect.Descriptor instead.
func (*AddRegistererRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{2}
}

func (x *AddRegistererRequest) GetRegisterer() *Registerer {
	if x != nil {
		return x.Registerer
	}
	return nil
}

type AddRegistererResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddRegistererResponse) Reset() {
	*x = AddRegistererResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRegistererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRegistererResponse) ProtoMessage() {}

func (x *AddRegistererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRegistererResponse.ProtoReflect.Descriptor instead.
func (*AddRegistererResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{3}
}

//사용자 정보 수정
type UpdateRegistererRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registerer *Registerer `protobuf:"bytes,2,opt,name=registerer,proto3" json:"registerer,omitempty"`
}

func (x *UpdateRegistererRequest) Reset() {
	*x = UpdateRegistererRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRegistererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistererRequest) ProtoMessage() {}

func (x *UpdateRegistererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistererRequest.ProtoReflect.Descriptor instead.
func (*UpdateRegistererRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRegistererRequest) GetRegisterer() *Registerer {
	if x != nil {
		return x.Registerer
	}
	return nil
}

type UpdateRegistererResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRegistererResponse) Reset() {
	*x = UpdateRegistererResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRegistererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRegistererResponse) ProtoMessage() {}

func (x *UpdateRegistererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRegistererResponse.ProtoReflect.Descriptor instead.
func (*UpdateRegistererResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{5}
}

//사용자 삭제
type DeleteRegistererRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistererId uint64 `protobuf:"varint,1,opt,name=registerer_id,json=registererId,proto3" json:"registerer_id,omitempty"`
}

func (x *DeleteRegistererRequest) Reset() {
	*x = DeleteRegistererRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRegistererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegistererRequest) ProtoMessage() {}

func (x *DeleteRegistererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegistererRequest.ProtoReflect.Descriptor instead.
func (*DeleteRegistererRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRegistererRequest) GetRegistererId() uint64 {
	if x != nil {
		return x.RegistererId
	}
	return 0
}

type DeleteRegistererResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRegistererResponse) Reset() {
	*x = DeleteRegistererResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRegistererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRegistererResponse) ProtoMessage() {}

func (x *DeleteRegistererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRegistererResponse.ProtoReflect.Descriptor instead.
func (*DeleteRegistererResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{7}
}

// 사용자 가져오기
type GetRegistererRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistererId uint64 `protobuf:"varint,1,opt,name=registerer_id,json=registererId,proto3" json:"registerer_id,omitempty"`
}

func (x *GetRegistererRequest) Reset() {
	*x = GetRegistererRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistererRequest) ProtoMessage() {}

func (x *GetRegistererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistererRequest.ProtoReflect.Descriptor instead.
func (*GetRegistererRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{8}
}

func (x *GetRegistererRequest) GetRegistererId() uint64 {
	if x != nil {
		return x.RegistererId
	}
	return 0
}

type GetRegistererResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Registerer *Registerer `protobuf:"bytes,1,opt,name=registerer,proto3" json:"registerer,omitempty"`
}

func (x *GetRegistererResponse) Reset() {
	*x = GetRegistererResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistererResponse) ProtoMessage() {}

func (x *GetRegistererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistererResponse.ProtoReflect.Descriptor instead.
func (*GetRegistererResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{9}
}

func (x *GetRegistererResponse) GetRegisterer() *Registerer {
	if x != nil {
		return x.Registerer
	}
	return nil
}

//축사 별 사용자 리스트 가져오기
type GetRegistererListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId uint64 `protobuf:"varint,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *GetRegistererListRequest) Reset() {
	*x = GetRegistererListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistererListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistererListRequest) ProtoMessage() {}

func (x *GetRegistererListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistererListRequest.ProtoReflect.Descriptor instead.
func (*GetRegistererListRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{10}
}

func (x *GetRegistererListRequest) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

type GetRegistererListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistererList []*Registerer `protobuf:"bytes,1,rep,name=registerer_list,json=registererList,proto3" json:"registerer_list,omitempty"`
}

func (x *GetRegistererListResponse) Reset() {
	*x = GetRegistererListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRegistererListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistererListResponse) ProtoMessage() {}

func (x *GetRegistererListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistererListResponse.ProtoReflect.Descriptor instead.
func (*GetRegistererListResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{11}
}

func (x *GetRegistererListResponse) GetRegistererList() []*Registerer {
	if x != nil {
		return x.RegistererList
	}
	return nil
}

// 축사 정보 획득
type GetBarnRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId uint64 `protobuf:"varint,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *GetBarnRequest) Reset() {
	*x = GetBarnRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBarnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarnRequest) ProtoMessage() {}

func (x *GetBarnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarnRequest.ProtoReflect.Descriptor instead.
func (*GetBarnRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{12}
}

func (x *GetBarnRequest) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

type GetBarnResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Barn *Barn `protobuf:"bytes,1,opt,name=barn,proto3" json:"barn,omitempty"`
}

func (x *GetBarnResponse) Reset() {
	*x = GetBarnResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBarnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarnResponse) ProtoMessage() {}

func (x *GetBarnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarnResponse.ProtoReflect.Descriptor instead.
func (*GetBarnResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{13}
}

func (x *GetBarnResponse) GetBarn() *Barn {
	if x != nil {
		return x.Barn
	}
	return nil
}

// 축사 목록 획득
type GetBarnListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBarnListRequest) Reset() {
	*x = GetBarnListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBarnListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarnListRequest) ProtoMessage() {}

func (x *GetBarnListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarnListRequest.ProtoReflect.Descriptor instead.
func (*GetBarnListRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{14}
}

type GetBarnListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnList []*Barn `protobuf:"bytes,1,rep,name=barn_list,json=barnList,proto3" json:"barn_list,omitempty"`
}

func (x *GetBarnListResponse) Reset() {
	*x = GetBarnListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBarnListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBarnListResponse) ProtoMessage() {}

func (x *GetBarnListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBarnListResponse.ProtoReflect.Descriptor instead.
func (*GetBarnListResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{15}
}

func (x *GetBarnListResponse) GetBarnList() []*Barn {
	if x != nil {
		return x.BarnList
	}
	return nil
}

// 축사 로그 획득
// 내 축사에 누가 언제 들어왔었는지 획득
type GetAccessLogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId uint64 `protobuf:"varint,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *GetAccessLogRequest) Reset() {
	*x = GetAccessLogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessLogRequest) ProtoMessage() {}

func (x *GetAccessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessLogRequest.ProtoReflect.Descriptor instead.
func (*GetAccessLogRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{16}
}

func (x *GetAccessLogRequest) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

type GetAccessLogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessLog []*AccessLog `protobuf:"bytes,1,rep,name=access_log,json=accessLog,proto3" json:"access_log,omitempty"`
}

func (x *GetAccessLogResponse) Reset() {
	*x = GetAccessLogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessLogResponse) ProtoMessage() {}

func (x *GetAccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessLogResponse.ProtoReflect.Descriptor instead.
func (*GetAccessLogResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{17}
}

func (x *GetAccessLogResponse) GetAccessLog() []*AccessLog {
	if x != nil {
		return x.AccessLog
	}
	return nil
}

type AccessLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId      uint64 `protobuf:"varint,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
	PlateNumber string `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	AccessTime  string `protobuf:"bytes,3,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	IsOpened    bool   `protobuf:"varint,4,opt,name=is_opened,json=isOpened,proto3" json:"is_opened,omitempty"`
	Note        string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
}

func (x *AccessLog) Reset() {
	*x = AccessLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLog) ProtoMessage() {}

func (x *AccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLog.ProtoReflect.Descriptor instead.
func (*AccessLog) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{18}
}

func (x *AccessLog) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

func (x *AccessLog) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *AccessLog) GetAccessTime() string {
	if x != nil {
		return x.AccessTime
	}
	return ""
}

func (x *AccessLog) GetIsOpened() bool {
	if x != nil {
		return x.IsOpened
	}
	return false
}

func (x *AccessLog) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

// 사용자가 앱에서 축사 문열어달라고 요청하는 메시지
type OpenGateFromAppRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BarnId uint64 `protobuf:"varint,1,opt,name=barn_id,json=barnId,proto3" json:"barn_id,omitempty"`
}

func (x *OpenGateFromAppRequest) Reset() {
	*x = OpenGateFromAppRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenGateFromAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenGateFromAppRequest) ProtoMessage() {}

func (x *OpenGateFromAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenGateFromAppRequest.ProtoReflect.Descriptor instead.
func (*OpenGateFromAppRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{19}
}

func (x *OpenGateFromAppRequest) GetBarnId() uint64 {
	if x != nil {
		return x.BarnId
	}
	return 0
}

type OpenGateFromAppResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenGateFromAppResponse) Reset() {
	*x = OpenGateFromAppResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenGateFromAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenGateFromAppResponse) ProtoMessage() {}

func (x *OpenGateFromAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenGateFromAppResponse.ProtoReflect.Descriptor instead.
func (*OpenGateFromAppResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{20}
}

// 엣지에서 번호판 인식 후 열어달라고 요청하는 메시지
type AccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerSerial string `protobuf:"bytes,1,opt,name=controller_serial,json=controllerSerial,proto3" json:"controller_serial,omitempty"`
	PlateNumber      string `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	Image            []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{21}
}

func (x *AccessRequest) GetControllerSerial() string {
	if x != nil {
		return x.ControllerSerial
	}
	return ""
}

func (x *AccessRequest) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *AccessRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type AccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open bool `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
}

func (x *AccessResponse) Reset() {
	*x = AccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_main_control_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessResponse) ProtoMessage() {}

func (x *AccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_main_control_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessResponse.ProtoReflect.Descriptor instead.
func (*AccessResponse) Descriptor() ([]byte, []int) {
	return file_main_control_proto_rawDescGZIP(), []int{22}
}

func (x *AccessResponse) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

var File_main_control_proto protoreflect.FileDescriptor

var file_main_control_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x22, 0xff, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x6f, 0x74, 0x65, 0x22, 0xb4, 0x03, 0x0a, 0x04, 0x42, 0x61, 0x72, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x42, 0x61, 0x72, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x2d, 0x0a, 0x12, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52,
	0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x41,
	0x64, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x52, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x37, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3e, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x49, 0x64, 0x22, 0x50, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x72, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x22,
	0x33, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62,
	0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61,
	0x72, 0x6e, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x72, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x29, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6e, 0x49, 0x64, 0x22, 0x38,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x61, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x42, 0x61,
	0x72, 0x6e, 0x52, 0x04, 0x62, 0x61, 0x72, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42,
	0x61, 0x72, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x42, 0x61, 0x72, 0x6e, 0x52, 0x08, 0x62, 0x61, 0x72,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62,
	0x61, 0x72, 0x6e, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x09, 0x61, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x4c, 0x6f, 0x67, 0x22, 0x99, 0x01, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c,
	0x6f, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x72, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70,
	0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65,
	0x22, 0x31, 0x0a, 0x16, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x61,
	0x72, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x61, 0x72,
	0x6e, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61, 0x74, 0x65, 0x46,
	0x72, 0x6f, 0x6d, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x75,
	0x0a, 0x0d, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x2a, 0x9c, 0x01, 0x0a, 0x10,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x21, 0x0a, 0x1d, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x52, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x24, 0x0a, 0x20, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45,
	0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x47,
	0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x52, 0x45, 0x47,
	0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x44, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x57, 0x0a, 0x0a, 0x42, 0x61,
	0x72, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x41, 0x52, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x41, 0x52, 0x4e, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x41, 0x46, 0x45, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x42,
	0x41, 0x52, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x41, 0x46,
	0x45, 0x10, 0x02, 0x32, 0x85, 0x07, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x12, 0x58, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a,
	0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65,
	0x72, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x72, 0x12, 0x24, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x25, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x6e, 0x12, 0x1b,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x61, 0x72, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x42, 0x61, 0x72, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x72,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x12,
	0x20, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61,
	0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x70, 0x70, 0x12, 0x23, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x47, 0x61, 0x74, 0x65,
	0x46, 0x72, 0x6f, 0x6d, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x4f, 0x70, 0x65,
	0x6e, 0x47, 0x61, 0x74, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x1a, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x5a, 0x0a, 0x1b, 0x6e,
	0x65, 0x74, 0x2e, 0x69, 0x6a, 0x6f, 0x6f, 0x6e, 0x2e, 0x62, 0x61, 0x63, 0x73, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x42, 0x10, 0x4d, 0x61, 0x69, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x6e, 0x6f, 0x62,
	0x65, 0x69, 0x2f, 0x69, 0x64, 0x6c, 0x2f, 0x62, 0x61, 0x63, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x6e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_main_control_proto_rawDescOnce sync.Once
	file_main_control_proto_rawDescData = file_main_control_proto_rawDesc
)

func file_main_control_proto_rawDescGZIP() []byte {
	file_main_control_proto_rawDescOnce.Do(func() {
		file_main_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_main_control_proto_rawDescData)
	})
	return file_main_control_proto_rawDescData
}

var file_main_control_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_main_control_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_main_control_proto_goTypes = []interface{}{
	(RegistererStatus)(0),             // 0: maincontrol.RegistererStatus
	(BarnStatus)(0),                   // 1: maincontrol.BarnStatus
	(*Registerer)(nil),                // 2: maincontrol.Registerer
	(*Barn)(nil),                      // 3: maincontrol.Barn
	(*AddRegistererRequest)(nil),      // 4: maincontrol.AddRegistererRequest
	(*AddRegistererResponse)(nil),     // 5: maincontrol.AddRegistererResponse
	(*UpdateRegistererRequest)(nil),   // 6: maincontrol.UpdateRegistererRequest
	(*UpdateRegistererResponse)(nil),  // 7: maincontrol.UpdateRegistererResponse
	(*DeleteRegistererRequest)(nil),   // 8: maincontrol.DeleteRegistererRequest
	(*DeleteRegistererResponse)(nil),  // 9: maincontrol.DeleteRegistererResponse
	(*GetRegistererRequest)(nil),      // 10: maincontrol.GetRegistererRequest
	(*GetRegistererResponse)(nil),     // 11: maincontrol.GetRegistererResponse
	(*GetRegistererListRequest)(nil),  // 12: maincontrol.GetRegistererListRequest
	(*GetRegistererListResponse)(nil), // 13: maincontrol.GetRegistererListResponse
	(*GetBarnRequest)(nil),            // 14: maincontrol.GetBarnRequest
	(*GetBarnResponse)(nil),           // 15: maincontrol.GetBarnResponse
	(*GetBarnListRequest)(nil),        // 16: maincontrol.GetBarnListRequest
	(*GetBarnListResponse)(nil),       // 17: maincontrol.GetBarnListResponse
	(*GetAccessLogRequest)(nil),       // 18: maincontrol.GetAccessLogRequest
	(*GetAccessLogResponse)(nil),      // 19: maincontrol.GetAccessLogResponse
	(*AccessLog)(nil),                 // 20: maincontrol.AccessLog
	(*OpenGateFromAppRequest)(nil),    // 21: maincontrol.OpenGateFromAppRequest
	(*OpenGateFromAppResponse)(nil),   // 22: maincontrol.OpenGateFromAppResponse
	(*AccessRequest)(nil),             // 23: maincontrol.AccessRequest
	(*AccessResponse)(nil),            // 24: maincontrol.AccessResponse
}
var file_main_control_proto_depIdxs = []int32{
	0,  // 0: maincontrol.Registerer.status:type_name -> maincontrol.RegistererStatus
	1,  // 1: maincontrol.Barn.status:type_name -> maincontrol.BarnStatus
	2,  // 2: maincontrol.AddRegistererRequest.registerer:type_name -> maincontrol.Registerer
	2,  // 3: maincontrol.UpdateRegistererRequest.registerer:type_name -> maincontrol.Registerer
	2,  // 4: maincontrol.GetRegistererResponse.registerer:type_name -> maincontrol.Registerer
	2,  // 5: maincontrol.GetRegistererListResponse.registerer_list:type_name -> maincontrol.Registerer
	3,  // 6: maincontrol.GetBarnResponse.barn:type_name -> maincontrol.Barn
	3,  // 7: maincontrol.GetBarnListResponse.barn_list:type_name -> maincontrol.Barn
	20, // 8: maincontrol.GetAccessLogResponse.access_log:type_name -> maincontrol.AccessLog
	4,  // 9: maincontrol.MainControl.AddRegisterer:input_type -> maincontrol.AddRegistererRequest
	6,  // 10: maincontrol.MainControl.UpdateRegisterer:input_type -> maincontrol.UpdateRegistererRequest
	8,  // 11: maincontrol.MainControl.DeleteRegisterer:input_type -> maincontrol.DeleteRegistererRequest
	10, // 12: maincontrol.MainControl.GetRegisterer:input_type -> maincontrol.GetRegistererRequest
	12, // 13: maincontrol.MainControl.GetRegistererList:input_type -> maincontrol.GetRegistererListRequest
	14, // 14: maincontrol.MainControl.GetBarn:input_type -> maincontrol.GetBarnRequest
	16, // 15: maincontrol.MainControl.GetBarnList:input_type -> maincontrol.GetBarnListRequest
	18, // 16: maincontrol.MainControl.GetAccessLog:input_type -> maincontrol.GetAccessLogRequest
	21, // 17: maincontrol.MainControl.OpenGateFromApp:input_type -> maincontrol.OpenGateFromAppRequest
	23, // 18: maincontrol.MainControl.Access:input_type -> maincontrol.AccessRequest
	5,  // 19: maincontrol.MainControl.AddRegisterer:output_type -> maincontrol.AddRegistererResponse
	7,  // 20: maincontrol.MainControl.UpdateRegisterer:output_type -> maincontrol.UpdateRegistererResponse
	9,  // 21: maincontrol.MainControl.DeleteRegisterer:output_type -> maincontrol.DeleteRegistererResponse
	11, // 22: maincontrol.MainControl.GetRegisterer:output_type -> maincontrol.GetRegistererResponse
	13, // 23: maincontrol.MainControl.GetRegistererList:output_type -> maincontrol.GetRegistererListResponse
	15, // 24: maincontrol.MainControl.GetBarn:output_type -> maincontrol.GetBarnResponse
	17, // 25: maincontrol.MainControl.GetBarnList:output_type -> maincontrol.GetBarnListResponse
	19, // 26: maincontrol.MainControl.GetAccessLog:output_type -> maincontrol.GetAccessLogResponse
	22, // 27: maincontrol.MainControl.OpenGateFromApp:output_type -> maincontrol.OpenGateFromAppResponse
	24, // 28: maincontrol.MainControl.Access:output_type -> maincontrol.AccessResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_main_control_proto_init() }
func file_main_control_proto_init() {
	if File_main_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_main_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Registerer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Barn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRegistererRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRegistererResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRegistererRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRegistererResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRegistererRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRegistererResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistererRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistererResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistererListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRegistererListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBarnRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBarnResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBarnListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBarnListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessLogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccessLogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenGateFromAppRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenGateFromAppResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_main_control_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_main_control_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_main_control_proto_goTypes,
		DependencyIndexes: file_main_control_proto_depIdxs,
		EnumInfos:         file_main_control_proto_enumTypes,
		MessageInfos:      file_main_control_proto_msgTypes,
	}.Build()
	File_main_control_proto = out.File
	file_main_control_proto_rawDesc = nil
	file_main_control_proto_goTypes = nil
	file_main_control_proto_depIdxs = nil
}
